# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='origin',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
